### PR TITLE
test: Adding 100% coverage tests

### PR DESCRIPTION
**Pull request by kamilogorek**
image

### CODE REVIEW

**Comment by HazAT** [comment]
Sweeeeeet!
Can we add codegov and a nice badge in the readme plz :)?
See https://github.com/getsentry/sentry-cordova/blob/master/package.json

**Comment by jan-auer** [comment]
@kamilogorek this is awesome. 👏  🍻  
Before merging, please just let me add some Travis config and see if it runs on CI.

**Comment by kamilogorek** [comment]
@HazAT added Codecov and your lovely badge.
@jan-auer locked to node >v6 (Jest doesn't support <v6 as you already realized with Travis).

**Comment by kamilogorek** [comment]
THAT ONE LINE! https://codecov.io/gh/getsentry/sentry-webpack-plugin/src/master/src/index.js

**Comment by HazAT** [comment]
@kamilogorek  🎉 
But shouldn't be this one line "easy" to test?
Just pass in some garbage it should throw an error then?!

**Comment by kamilogorek** [comment]
@HazAT Nothing is easy in JavaScript tooling world :D I'll get it working!

**Comment by kamilogorek** [comment]
Ship it! :shipit:

**Comment by kamilogorek** [comment]
image

**Pull request merged**
