### PR TITLE
feat: Add function to download CLI binary

### PR DESCRIPTION
**Pull request by lforst**
Export `downloadCliBinary` to download the CLI binary so it can be installed during build-time.

### CODE REVIEW

**Review by Lms24 — COMMENTED** [review]
Shouldn't the plugin call the the CLI's download functionality (rather than or in addition to exporting it)?

**Comment by lforst** [comment]
> Shouldn't the plugin call the the CLI's download functionality (rather than or in addition to exporting it)?

It could, however, I would rather be able to do this from the outside in order to have more elaborate logging and error handling. For instance, if the download fails, I may not want to crash and simply skip uploading.

**Review by Lms24 — APPROVED** [review]
:shipit:

**Comment by lforst** [comment]
As discussed offline, we'll for now do it this way and trial it in Next.js. If we see that it sustainably solves issues we will port this functionality to the newer plugins. If we don't have properly distributed binaries by then.

**Pull request merged**
