### PR TITLE
Fix options context

### LINKED ISSUE #11: Webpack compatibility
Hi!

Is this plugin compatible with webpack 1.14.0?
It is throwing this error: `ERROR in Sentry CLI Plugin: Cannot read property 'include' of undefined`.

When logging `this.options` just before calling SentryCLI I got my webpack configuration instead of just the options in the plugin, I guess in webpack 1.14 `options` it is a reserved key.

My only options would be upgrade webpack, right?

### PR DESCRIPTION
**Pull request by montogeek**
`this` had another context, I just save a new reference in the correct context.
Fixes #11

### CODE REVIEW

**Comment by kamilogorek** [comment]
Thanks!

**Comment by kamilogorek** [comment]
cc @jan-auer

**Comment by montogeek** [comment]
Sorry, I completely missed it

**Comment by mgwidmann** [comment]
Would like to see a release for this fix, version `1.1.1` is broken at the moment. Not sure if downgrading webpack or something else would be a workaround but that isn't an option for me so I'd prefer to be off of using master directly.

**Comment by montogeek** [comment]
Downgrade to v1.1.0 if you dont need any special option

**Comment by jan-auer** [comment]
Released `@sentry/webpack-plugin 1.1.2`

**Pull request merged**
