### PR TITLE
deps: add missing peerDep

### PR DESCRIPTION
**Pull request by m1heng**
add webpack as peerDependency as webpack is used in index.d.ts for typing
https://github.com/getsentry/sentry-webpack-plugin/blob/4e85f797a4b9736c7d52e99c30c5dd933f3b4c3e/index.d.ts#L1

### CODE REVIEW

**Review by kamilogorek — APPROVED** [review]
Thanks

**Comment by rchl** [comment]
I'm not sure about that change... Not sure if when the usage of a dependency is only within types then that warrants a peer dependency.

This forces NPM to install the webpack dependency in projects that use `@sentry/webpack-plugin`. And if the `@sentry/webpack-plugin` is a production dependency then `webpack` is also installed in production, adding to the weight of the artifact.

Types are not really a requirement for using this package, thus I'm not sure if this is really a correct change.

You could say that if I don't want `webpack` included in production then I should not install `@sentry/webpack-plugin` as a production dependency. But what about the case when using `@nuxtjs/sentry` package? It currently comes with `@sentry/webpack-plugin` as a production dependency but another option would be to mark `@sentry/webpack-plugin` as a peer dependency there too but then I would have again the same problem there -- since the `@nuxtjs/sentry` is a production dependency then both `@sentry/webpack-plugin` and `webpack` would be installed as a production dependencies.

I'm not sure what are the typical conventions in those kind of scenarios but somethings feels off about this change due to how NPM handles such cases.

**Comment by rchl** [comment]
I guess I could also add an argument that Webpack 4 doesn't come with types (the types are provided through `@types/webpack`) so when using version 4, it's not even necessary to have it installed.

**Comment by kamilogorek** [comment]
Sounds reasonable, however, it would be still somewhat useful to provide this information to the end user.
One way to do this would be to use `peerDependenciesMeta` and mark `webpack` as optional. WDYT?

**Comment by rchl** [comment]
Based on my past experience, I don't think that would work. The npm would still install the dependency as a production one. It would just not complain if it failed installing.

**Comment by AbhiPrasad** [comment]
> Based on my past experience, I don't think that would work. The npm would still install the dependency as a production one. It would just not complain if it failed installing.

As per https://github.com/npm/rfcs/issues/221#issuecomment-695127530, setting `optional: true` will make sure the peer dependency does not get automatically installed. 

I am in favour of using `peerDependenciesMeta` with `optional` true here.

**Comment by rchl** [comment]
I'm all for trying and would be glad if it worked .

**Comment by rchl** [comment]
Note that `webpack` dependency exists in the project since it's a Nuxt project so it comes with `webpack`. I guess it wouldn't be a problem if `webpack` would not be present in the first place.

**Pull request merged**
